### ISSUE TITLE
ImageOnMap 3.1 on Paper 1.12.2 - Putting splatter map in a chest and rebooting breaks the map

### ISSUE THREAD

**Issue by TomLewis** [zDevelopers/ImageOnMap#123]
Ahoy

I'm stuck on 3.1 as I use Paper 1.12.2, so not sure if this has been fixed in later versions.
Reporting anyway.

Splatter maps, if you put one in a chest then reboot the server, they dont save, they just turn into the lower left map.
Before restart. 
![2020-09-15_19 54 35](https://user-images.githubusercontent.com/144046/93252900-046eac00-f78e-11ea-92b7-a915f18714d0.png)
After Restart
![2020-09-15_19 56 15](https://user-images.githubusercontent.com/144046/93252920-0b95ba00-f78e-11ea-9b34-d8b95b14d94a.png)

**Comment by Vlammar** [comment]
Old version, this issue is fixed in more recent one. I won't have the time to fix this issue, sorry.

**Comment by TomLewis** [comment]
Hello, im now using the latest PurPur 1.18.1 AND the latest ImageOnMap 4.2.2 and this issue still persists.

**Comment by TomLewis** [comment]
Bump.
