### ISSUE TITLE
Wrong resize.

### ISSUE THREAD

**Issue by MetalGearDaner** [zDevelopers/ImageOnMap#7]
Using the latest build from: http://jenkins.carrade.eu/job/ImageOnMap/, the plugin resize wrongly all the images. Here is a proof:

http://prntscr.com/6bf3db

**Comment by Coutume** [comment]
Can you paste the link to your image please ?

**Comment by MetalGearDaner** [comment]
http://i261.photobucket.com/albums/ii46/sarins/Minecraft/wordlcraft.jpg

**Comment by prokopyl** [comment]
Revision a5d019373601989c9a028df7d1d803257ae527c3 should fix this problem, can you confirm ?

**Comment by prokopyl** [comment]
This seems to be fixed now.

**Comment by lasercar** [comment]
Using version 2.99 and this is still a problem. Is there a newer build?

**Comment by AmauryCarrade** [comment]
We are still working on this here: #19. But these changes are unrelated, so this bug is unlikely to be fixed in the above PR.

Ping @prokopyl.

**Comment by prokopyl** [comment]
The fix has regressed, this is now fixed in commit b5751f3, and will be merged into the next alpha release.
